# Generated by Django 2.2.5 on 2020-05-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200521_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAsk',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.DeleteModel(
            name='CourseComments',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
